name: Upload APK to VPS and Send Telegram Message

on:
  push:
    branches:
      - release-tele

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate QR code
        run: |
          sudo apt-get update && sudo apt-get install -y qrencode
          qrencode -o qrcode.png "$APK_URL"

      - name: Send download link + QR to Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d text="[Hi-Study] APK mới đã được upload tại: $APK_URL \n Website: https://hi-study.futu.site/"

          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendPhoto" \
            -F chat_id="$TELEGRAM_CHAT_ID" \
            -F photo="@qrcode.png"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    env:
      APK_URL: ${{ secrets.APK_URL }}
